apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-core-deployment
  labels:
    app: frontend-core
spec:
  replicas: 1 # Define the number of replicas here
  selector:
    matchLabels:
      app: frontend-core
  template:
    metadata:
      labels:
        app: frontend-core
    spec:
      containers:
        - name: frontend-core
          image: sospy/puppylove-frontend:1.21
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-core-config
